// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zojmcdkvqzrqljdxsjkr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpvam1jZGt2cXpycWxqZHhzamtyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0MjQ2OTgsImV4cCI6MjA3MDAwMDY5OH0.n7uiSFz2jQNxRnUCVtmEJ46guFa8kg6VFZAuk-nh5A8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});